<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Button_Submit</description>
   <name>Button_Submit</name>
   <tag></tag>
   <elementGuidId>6a57a0bc-5e70-48e7-8378-7e15aab470f4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;submit&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
