<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Button_Upload</description>
   <name>Button_Upload</name>
   <tag></tag>
   <elementGuidId>caba7799-20c0-43aa-8758-09360883fe38</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;uploadPicture&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
