<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>CheckBox_Sports</description>
   <name>CheckBox_Sports</name>
   <tag></tag>
   <elementGuidId>1ca15efe-64ab-4430-8428-f890fb620bcd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='hobbiesWrapper']/div[2]/div[1]/label</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
