<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>DatePicker_Day</description>
   <name>DatePicker_Day</name>
   <tag></tag>
   <elementGuidId>f957a215-cb09-4c52-b615-1c4dfbe57f11</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[2]/div/div/div[2]/div[2]/div[1]/form/div[5]/div[2]/div[2]/div[2]/div/div/div[2]/div[2]/div[4]/div[7]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
