<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>DatePicker_Month</description>
   <name>DatePicker_Year</name>
   <tag></tag>
   <elementGuidId>2cf84ad9-ae14-43a9-aa92-c916b4e0a52b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[2]/div/div/div[2]/div[2]/div[1]/form/div[5]/div[2]/div[2]/div[2]/div/div/div[2]/div[1]/div[2]/div[2]/select</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
