<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>DatePicker_Month</description>
   <name>DatePicker_Month</name>
   <tag></tag>
   <elementGuidId>50d294ef-c95e-4005-8489-400a176f0fa9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@class='react-datepicker__month-select']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
