<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>DatePicker_Month</description>
   <name>DatePicker_Month</name>
   <tag></tag>
   <elementGuidId>50d294ef-c95e-4005-8489-400a176f0fa9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[2]/div/div/div[2]/div[2]/div[1]/form/div[5]/div[2]/div[2]/div[2]/div/div/div[2]/div[1]/div[2]/div[1]/select</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
