<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>DropDownList_State</description>
   <name>DropDownList_State-Option2</name>
   <tag></tag>
   <elementGuidId>805cdc1d-1548-42f9-9684-ade1510a74ec</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='react-select-3-option-1']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
