<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>DropDownList_State</description>
   <name>DropDownList_City</name>
   <tag></tag>
   <elementGuidId>0254b812-ff82-474e-a3de-bfbbc4c6bc1d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;city&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
