<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>DropDownList_State</description>
   <name>DropDownList_City-Option1</name>
   <tag></tag>
   <elementGuidId>88336b6d-2bb3-4042-892d-ed42fd28ced1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='react-select-4-option-0']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
