<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>RadioButton_Male</description>
   <name>RadioButton_Other</name>
   <tag></tag>
   <elementGuidId>65eb978f-37ce-43bc-bf38-6d69e738a9d4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='gender-radio-3']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
