<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>RadioButton_Male</description>
   <name>RadioButton_Female</name>
   <tag></tag>
   <elementGuidId>310bfa21-f108-4783-91c2-d3fc23d27793</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='genterWrapper']/div[2]/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
