<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>RadioButton_Male</description>
   <name>RadioButton_Male</name>
   <tag></tag>
   <elementGuidId>86bde122-ad9f-4167-800f-55d6ddd31a5e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='genterWrapper']/div[2]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
