<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>TextArea_CurrentAddress</description>
   <name>TextArea_CurrentAddress</name>
   <tag></tag>
   <elementGuidId>6035b77d-1032-45f7-b66d-50d77cba30df</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;currentAddress&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
