<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>TextBox_FirstName</description>
   <name>TextBox_FirstName</name>
   <tag></tag>
   <elementGuidId>5e195902-f22c-4303-af16-5a0f0cee64e0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='firstName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
