<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>TextBox_FirstName</description>
   <name>TextBox_UserEmail</name>
   <tag></tag>
   <elementGuidId>130832a3-2b4f-4eea-ba76-adc3e3a52909</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='userEmail']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
