<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>TextBox_FirstName</description>
   <name>TextBox_LastName</name>
   <tag></tag>
   <elementGuidId>af8102b8-c6ca-4815-873d-7d3bb12728ef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='lastName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
