<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>TextBox_Subjects</description>
   <name>TextBox_Subjects</name>
   <tag></tag>
   <elementGuidId>19faaa2c-14b2-48b4-b3ef-de906ed908a6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='subjectsInput']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
