<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>TextBox_DateOfBirth</description>
   <name>TextBox_DateOfBirth</name>
   <tag></tag>
   <elementGuidId>ab039108-f012-43a3-98be-d2f070bd4a88</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id=&quot;dateOfBirthInput&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
