<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>TextBox_MobileNumber</description>
   <name>TextBox_MobileNumber</name>
   <tag></tag>
   <elementGuidId>772164e4-252d-4f2e-a2f8-f4cacc1e5f24</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='userNumber']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
